# Generated by Django 5.0.6 on 2024-05-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
