# Generated by Django 5.0.6 on 2024-05-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0002_rename_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
