# Generated by Django 5.0.6 on 2024-05-31 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='animales',
        ),
    ]
