# Generated by Django 5.0.6 on 2024-05-31 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minimarket', '0003_delete_animales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre_categoria', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='static/img')),
                ('nombre_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.categoria')),
            ],
        ),
    ]
