# Generated by Django 5.0.6 on 2024-06-19 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0006_cliente_alter_producto_imagen_detallecompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='formularioContacto',
            fields=[
                ('id_formulario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_solicitud', models.CharField(choices=[('consulta', 'Consulta'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('otro', 'Otro')], max_length=10)),
                ('comentario', models.CharField(max_length=300)),
            ],
        ),
    ]
