# Generated by Django 5.0.6 on 2024-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0007_formulariocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocontacto',
            name='id_formulario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='tipo_solicitud',
            field=models.CharField(choices=[('CONS', 'Consulta'), ('REC', 'Reclamo'), ('SUG', 'Sugerencia'), ('OTRO', 'Otro')], max_length=10),
        ),
    ]
