# Generated by Django 5.0.6 on 2024-06-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0008_alter_formulariocontacto_id_formulario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocontacto',
            name='tipo_solicitud',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('RECLAMO', 'Reclamo'), ('SUGERENCIA', 'Sugerencia'), ('OTRO', 'Otro')], max_length=10),
        ),
    ]
