# Generated by Django 5.0.6 on 2024-07-13 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0009_alter_formulariocontacto_tipo_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='direccion_cliente',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='email_cliente',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='nombre',
            field=models.BinaryField(),
        ),
    ]
